# Generated by Django 5.1.7 on 2025-12-07 19:16

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('allergens', models.CharField(blank=True, max_length=255)),
                ('base_unit', models.CharField(choices=[('g', 'grams (g)'), ('kg', 'kilograms (kg)'), ('ml', 'milliliters (ml)'), ('l', 'liters (l)'), ('piece', 'piece'), ('tsp', 'teaspoon'), ('tbsp', 'tablespoon'), ('cup', 'cup')], max_length=20)),
                ('base_amount', models.FloatField(help_text='Amount of base_unit used for calorie calculation (e.g. 100 g, 100 ml, 1 piece)')),
                ('calories_per_base_amount', models.FloatField(help_text='Calories for the base amount (e.g. kcal per 100 g)')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('servings', models.PositiveIntegerField(default=1)),
                ('preparation_time', models.PositiveIntegerField(help_text='Minutes')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientDiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_recipe_app.diet')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_recipe_app.ingredient')),
            ],
            options={
                'unique_together': {('ingredient', 'diet')},
            },
        ),
        migrations.AddField(
            model_name='ingredient',
            name='diets',
            field=models.ManyToManyField(related_name='ingredients', through='smart_recipe_app.IngredientDiet', to='smart_recipe_app.diet'),
        ),
        migrations.CreateModel(
            name='Pantry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pantry', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('wanted_calories', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_plans', to=settings.AUTH_USER_MODEL)),
                ('recipes', models.ManyToManyField(blank=True, related_name='daily_plans', to='smart_recipe_app.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_recipe_app.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_recipe_app.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='smart_recipe_app.RecipeIngredient', to='smart_recipe_app.ingredient'),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipes', models.ManyToManyField(blank=True, related_name='wishlists', to='smart_recipe_app.recipe')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PantryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('base_unit', models.CharField(max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('ml_scan', 'ML scan')], default='manual', max_length=20)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_recipe_app.ingredient')),
                ('pantry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='smart_recipe_app.pantry')),
            ],
            options={
                'unique_together': {('pantry', 'ingredient')},
            },
        ),
    ]
