# Generated by Django 5.1.7 on 2025-12-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_recipe_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pantryitem',
            name='base_unit',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
