# Generated by Django 4.2.26 on 2025-12-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_recipe_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pantryitemrelation',
            name='uniq_pantry_ingredient',
        ),
        migrations.AddConstraint(
            model_name='pantryitemrelation',
            constraint=models.UniqueConstraint(fields=('pantry', 'ingredient'), name='uniq_pantry_ingredient'),
        ),
    ]
