# Generated by Django 4.2.26 on 2026-01-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_recipe_app', '0002_remove_pantryitemrelation_uniq_pantry_ingredient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pantryitemrelation',
            name='expires_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pantryitemrelation',
            name='is_opened',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pantryitemrelation',
            name='purchased_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
