# Generated by Django 4.2.26 on 2026-01-17 21:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smart_recipe_app', '0003_pantryitemrelation_expires_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PantryScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pantry_scans/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('raw_output', models.JSONField(blank=True, null=True)),
                ('ingredients_added_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_amount',
            field=models.FloatField(help_text='Amount of base_unit used for calorie calculation (e.g. 100 g, 100 ml, 1 piece)', validators=[django.core.validators.MinValueValidator(1e-06)]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='calories_per_base_amount',
            field=models.FloatField(help_text='Calories for the base amount (e.g. kcal per 100 g)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pantryitemrelation',
            name='quantity',
            field=models.FloatField(help_text='Amount in ingredient.base_unit (e.g., 200 g, 2 piece)', validators=[django.core.validators.MinValueValidator(1e-06)]),
        ),
        migrations.AlterField(
            model_name='recipeingredientrelation',
            name='quantity',
            field=models.FloatField(help_text='Amount in ingredient.base_unit (e.g., 200 g, 2 piece)', validators=[django.core.validators.MinValueValidator(1e-06)]),
        ),
        migrations.CreateModel(
            name='PantryScanDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('confidence', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('quantity_guess', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('matched_ingredient', models.ForeignKey(blank=True, help_text='Ingredient you matched this detection to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='smart_recipe_app.ingredient')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='smart_recipe_app.pantryscan')),
            ],
            options={
                'ordering': ['-confidence'],
            },
        ),
        migrations.AddIndex(
            model_name='pantryscan',
            index=models.Index(fields=['user', '-created_at'], name='smart_recip_user_id_3ce8a6_idx'),
        ),
        migrations.AddIndex(
            model_name='pantryscan',
            index=models.Index(fields=['status'], name='smart_recip_status_2faa8b_idx'),
        ),
    ]
