# Generated by Django 4.2.26 on 2026-01-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_recipe_app', '0005_alter_ingredient_base_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='base_unit',
            field=models.CharField(choices=[('g', 'grams (g)'), ('kg', 'kilograms (kg)'), ('ml', 'milliliters (ml)'), ('l', 'liters (l)'), ('pcs', 'pieces'), ('tsp', 'teaspoon'), ('tbsp', 'tablespoon'), ('cup', 'cup')], help_text='Mass units like kilograms (kg), grams (g), liters (l) and etc.', max_length=20),
        ),
    ]
