# Generated by Django 4.2.26 on 2026-01-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_recipe_app', '0006_alter_ingredient_base_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='description',
            field=models.TextField(blank=True, help_text='Brief explanation of this diet (e.g., what foods are allowed/excluded)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_unit',
            field=models.CharField(choices=[('g', 'grams (g)'), ('ml', 'milliliters (ml)'), ('pcs', 'pieces'), ('tsp', 'teaspoon'), ('tbsp', 'tablespoon'), ('cup', 'cup')], help_text='Mass units like kilograms (kg), grams (g), liters (l) and etc.', max_length=20),
        ),
    ]
