# Generated by Django 5.1.7 on 2026-02-02 14:06

from django.db import migrations


def create_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.get_or_create(name="User")
    Group.objects.get_or_create(name="Admin")

def remove_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name__in=["User", "Admin"]).delete()

class Migration(migrations.Migration):
    dependencies = [
        ('smart_recipe_app', '0007_diet_description_alter_ingredient_base_unit'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(create_groups, reverse_code=remove_groups),
    ]